In [1]:
import numpy as np 
import pandas as pd

In [18]:
complete_df = pd.read_csv(r'complete-dataset(4).csv')
complete_df = complete_df.drop(columns='Unnamed: 0',axis=1)
complete_df

,userId,movieId,rating,original_title,nltk_rating,diff,leniency_score_for_user
0,1,110,1.0,Three Colors: Red,4.571285,-3.571285,0.791561
1,1,147,4.5,The 400 Blows,3.709128,0.790872,0.791561
2,1,858,5.0,Sleepless in Seattle,4.667067,0.332933,0.791561
3,1,1246,5.0,Rocky Balboa,4.266597,0.733403,0.791561
4,1,1968,4.0,Fools Rush In,4.756418,-0.756418,0.791561
...,...,...,...,...,...,...,...
5001,1219,54503,5.0,The Mystery of Chess Boxing,2.425867,2.574133,0.620946
5002,1219,58559,1.0,Confession of a Child of the Century,2.535798,-1.535797,0.620946
5003,1219,260,1.0,The 39 Steps,4.341973,-3.341973,0.620946
5004,1219,780,1.0,The Passion of Joan of Arc,4.034362,-3.034362,0.620946
5005,1219,527,5.0,Once Were Warriors,2.769950,2.230050,0.620946

In [19]:
ratings_matrix = complete_df.pivot_table(index='userId',columns='movieId',values='rating').fillna(0)
ratings_matrix

movieId,5,25,58,64,79,110,141,147,223,260,...,1552,1968,2762,2959,3101,4226,4474,54503,58559,96821
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.5,0.0,0.0,...,0.0,4.0,4.5,4.0,0.0,4.0,0.0,3.5,4.0,5.0
2,3.0,3.0,3.0,4.0,4.0,0.0,3.0,0.0,0.0,4.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,5.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0
1214,5.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0
1216,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1219,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,5.0,1.0,0.0

In [20]:
import pandas as pd
nltk_ratings_matrix = pd.pivot_table(complete_df, values='nltk_rating', index='userId', columns='movieId').fillna(0)
nltk_ratings_matrix

movieId,5,25,58,64,79,110,141,147,223,260,...,1552,1968,2762,2959,3101,4226,4474,54503,58559,96821
userId,,,,,,,,,,,,,,,,,,,,,
1,0.00000,0.000000,0.000000,0.000000,0.00000,4.571285,0.000000,3.709128,0.000000,0.000000,...,0.00000,4.756418,3.598082,3.616755,0.00000,2.65913,0.000000,2.425867,2.535798,3.870065
2,3.64357,2.335647,4.063033,3.930747,2.87473,0.000000,3.810897,0.000000,0.000000,4.341973,...,3.91699,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
3,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,4.756418,0.000000,0.000000,3.51121,0.00000,3.838612,0.000000,0.000000,0.000000
4,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,3.461978,0.000000,...,0.00000,0.000000,3.598082,0.000000,0.00000,2.65913,0.000000,0.000000,0.000000,0.000000
5,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.00000,0.000000,0.000000,0.000000,0.00000,4.571285,0.000000,0.000000,0.000000,4.341973,...,0.00000,0.000000,0.000000,3.616755,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
1214,3.64357,0.000000,0.000000,3.930747,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
1215,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,4.341973,...,0.00000,0.000000,0.000000,0.000000,0.00000,2.65913,0.000000,0.000000,0.000000,0.000000
1216,0.00000,0.000000,0.000000,0.000000,0.00000,4.571285,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
1219,0.00000,0.000000,0.000000,0.000000,0.00000,4.571285,0.000000,0.000000,0.000000,4.341973,...,0.00000,0.000000,0.000000,0.000000,0.00000,2.65913,0.000000,2.425867,2.535798,0.000000

# Recommendations based on Cosine Similarity b/w users:

## (When user leniency score is not taken into account):

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim_matrix = cosine_similarity(ratings_matrix)
cosine_sim_matrix_df = pd.DataFrame(index=complete_df['userId'].unique(),columns=complete_df['userId'].unique())
cosine_sim_matrix_df.values[:,:] = cosine_sim_matrix
cosine_sim_matrix_df

,1,2,3,4,5,7,8,9,11,12,...,1207,1208,1209,1211,1212,1213,1214,1215,1216,1219
1,1.0,0.0,0.2561,0.25102,0.360141,0.477315,0.419518,0.563,0.367229,0.375382,...,0.806617,0.037753,0.360141,0.288113,0.0,0.141446,0.0,0.346706,0.056245,0.297306
2,0.0,1.0,0.0,0.115153,0.0,0.0,0.0,0.0,0.07854,0.139638,...,0.0,0.149374,0.0,0.0,0.651833,0.37814,0.480272,0.112749,0.0,0.053469
3,0.2561,0.0,1.0,0.0,0.444444,0.0,0.27735,0.0,0.372556,0.356348,...,0.185025,0.326133,0.444444,0.0,0.0,0.106149,0.132175,0.498199,0.277642,0.238247
4,0.25102,0.115153,0.0,1.0,0.0,0.0,0.280166,0.447192,0.069597,0.31497,...,0.294372,0.0,0.0,0.0,0.160727,0.128672,0.160221,0.139876,0.0,0.09747
5,0.360141,0.0,0.444444,0.0,1.0,0.0,0.0,0.0,0.0,0.356348,...,0.416305,0.0,1.0,0.0,0.0,0.0,0.0,0.593442,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.141446,0.37814,0.106149,0.128672,0.0,0.220477,0.0,0.0,0.458305,0.18913,...,0.154666,0.38946,0.0,0.371521,0.430683,1.0,0.399863,0.167982,0.372998,0.347101
1214,0.0,0.480272,0.132175,0.160221,0.0,0.0,0.0,0.0,0.127491,0.0,...,0.0,0.207836,0.0,0.0,0.220821,0.399863,1.0,0.0,0.0,0.042512
1215,0.346706,0.112749,0.498199,0.139876,0.593442,0.0,0.0,0.255418,0.433095,0.622668,...,0.439206,0.276487,0.593442,0.0,0.157372,0.167982,0.0,1.0,0.329529,0.473643
1216,0.056245,0.0,0.277642,0.0,0.0,0.0,0.0,0.0,0.509304,0.278261,...,0.0,0.736716,0.0,0.0,0.0,0.372998,0.0,0.329529,1.0,0.753461
1219,0.297306,0.053469,0.238247,0.09747,0.0,0.318119,0.0,0.177983,0.738656,0.286534,...,0.357061,0.56194,0.0,0.0,0.076763,0.347101,0.042512,0.473643,0.753461,1.0

## -> Use K Nearest Neighbour for finding top 5 similar users based on cosine similarity:

In [32]:
from sklearn.neighbors import NearestNeighbors

# fit a k-NN model on cosine similarity matrix
knn_model = NearestNeighbors(n_neighbors=6, metric='cosine', algorithm='brute')
knn_model.fit(cosine_sim_matrix_df)

def recommend_movies(user_id):
    
    # find the k-nearest neighbors of the user:
    _, indices = knn_model.kneighbors(cosine_sim_matrix_df.loc[[user_id]])
    similar_users = cosine_sim_matrix_df.iloc[indices[0], 1:]
    
    # get the movies not watched by the user:
    not_watched = ratings_matrix.loc[user_id][ratings_matrix.loc[user_id] == 0].index
    
    # create a dictionary to store the score of each not watched movie
    movie_scores = {}
    
    # iterate over each similar user
    for user in similar_users.index:
        
        # get the ratings of the user for not watched movies
        user_ratings = ratings_matrix.loc[user][not_watched]
        
        # calculate the cosine similarity score between the user and input user
        similarity_score = cosine_sim_matrix_df[user_id][user]
        
        # multiply the ratings with the similarity score and add to the movie_scores dictionary
        for movie, rating in user_ratings.items():
            if movie in movie_scores:
                movie_scores[movie] += rating * similarity_score
            else:
                movie_scores[movie] = rating * similarity_score
    
    # sort the movie_scores dictionary by value in descending order
    sorted_scores = sorted(movie_scores.items(), key=lambda x: x[1], reverse=True)
    
    # get the top 5 movies from the sorted_scores
    top_5_movies = [x[0] for x in sorted_scores[:5]]
    
    return top_5_movies
    

userId = 1
top_5_recommended_movies = recommend_movies(userId)
movie_titles = complete_df.loc[complete_df['movieId'].isin(top_5_recommended_movies), 'original_title'].tolist()
print(f"Recommended movies for {userId} are: ")
print()
unique_movie_titles = set(movie_titles)
for titles in unique_movie_titles:
    print(titles)

Recommended movies for 1 are:

Rebecca
Once Were Warriors
Four Rooms
Interview with the Vampire
The Passion of Joan of Arc

## (When user leniency score is taken into account):

In [25]:
# importing the csv that contains user leniency matrix created by taking into account the leniency score of each user
user_leniency_matrix = pd.read_csv(r'user_leniency_matrix.csv')
user_leniency_matrix = user_leniency_matrix.drop(columns='Unnamed: 0',axis=1)
user_leniency_matrix.index = user_leniency_matrix.columns
user_leniency_matrix

,1,2,3,4,5,7,8,9,11,12,...,1207,1208,1209,1211,1212,1213,1214,1215,1216,1219
1,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,...,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561,0.791561
2,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,...,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206,0.413206
3,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,...,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571,0.495571
4,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,...,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734,0.786734
5,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,...,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907,0.694907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,...,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671,0.591671
1214,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,...,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160,0.885160
1215,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,...,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246,0.701246
1216,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,...,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616,0.731616
1219,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,...,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946,0.620946

## To make the hybrid recommendation based on both user ratings and leniency score, first we create a new matrix ,whose values will be obtained by giving 55% weightage to cosine similarity (b/w that pair of users) and 45% weightage to leniency score of the user:

In [26]:
combined_score_matrix_cosine_and_leniency = 0.55 * cosine_sim_matrix + 0.45 * user_leniency_matrix
combined_score_matrix_cosine_and_leniency_df = pd.DataFrame(index=complete_df['userId'].unique(),columns=complete_df['userId'].unique())
combined_score_matrix_cosine_and_leniency_df.values[:,:] = combined_score_matrix_cosine_and_leniency
combined_score_matrix_cosine_and_leniency_df

,1,2,3,4,5,7,8,9,11,12,...,1207,1208,1209,1211,1212,1213,1214,1215,1216,1219
1,0.906202,0.356202,0.497057,0.494263,0.55428,0.618725,0.586937,0.665852,0.558178,0.562662,...,0.799841,0.376966,0.55428,0.514664,0.356202,0.433997,0.356202,0.546891,0.387137,0.519721
2,0.185943,0.735943,0.185943,0.249277,0.185943,0.185943,0.185943,0.185943,0.22914,0.262744,...,0.185943,0.268099,0.185943,0.185943,0.544451,0.39392,0.450092,0.247955,0.185943,0.215351
3,0.363862,0.223007,0.773007,0.223007,0.467451,0.223007,0.375549,0.223007,0.427912,0.418998,...,0.32477,0.40238,0.467451,0.223007,0.223007,0.281389,0.295703,0.497016,0.37571,0.354043
4,0.492091,0.417364,0.35403,0.90403,0.35403,0.35403,0.508121,0.599986,0.392308,0.527264,...,0.515935,0.35403,0.35403,0.35403,0.44243,0.4248,0.442151,0.430962,0.35403,0.407638
5,0.510786,0.312708,0.557153,0.312708,0.862708,0.312708,0.312708,0.312708,0.312708,0.5087,...,0.541676,0.312708,0.862708,0.312708,0.312708,0.312708,0.312708,0.639102,0.312708,0.312708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,0.344047,0.474229,0.324634,0.337022,0.266252,0.387514,0.266252,0.266252,0.51832,0.370274,...,0.351319,0.480455,0.266252,0.470589,0.503127,0.816252,0.486176,0.358642,0.471401,0.457158
1214,0.398322,0.662472,0.471018,0.486443,0.398322,0.398322,0.398322,0.398322,0.468442,0.398322,...,0.398322,0.512632,0.398322,0.398322,0.519774,0.618246,0.948322,0.398322,0.398322,0.421704
1215,0.506249,0.377573,0.58957,0.392492,0.641954,0.315561,0.315561,0.456041,0.553763,0.658028,...,0.557124,0.467629,0.641954,0.315561,0.402116,0.407951,0.315561,0.865561,0.496802,0.576065
1216,0.360162,0.329227,0.48193,0.329227,0.329227,0.329227,0.329227,0.329227,0.609345,0.482271,...,0.329227,0.734421,0.329227,0.329227,0.329227,0.534376,0.329227,0.510468,0.879227,0.743631
1219,0.442944,0.308834,0.410462,0.333034,0.279426,0.454391,0.279426,0.377316,0.685687,0.437019,...,0.475809,0.588492,0.279426,0.279426,0.321646,0.470331,0.302807,0.539929,0.693829,0.829426

## -> Use K Nearest Neighbour for finding top 5 similar users based on cosine similarity + leniency score:

In [33]:
from sklearn.neighbors import NearestNeighbors

knn_model = NearestNeighbors(n_neighbors=6, metric='cosine', algorithm='brute')
knn_model.fit(combined_score_matrix_cosine_and_leniency_df)

# function to get top 5 movies based on similar users
def recommend_movies(user_id):
    
    # get the top 10 similar users
    _, indices = knn_model.kneighbors(combined_score_matrix_cosine_and_leniency_df.loc[[user_id]])
    similar_users = combined_score_matrix_cosine_and_leniency_df.iloc[indices[0], 1:]
    
    
    # get the not watched movies of the user
    not_watched = ratings_matrix.loc[user_id][ratings_matrix.loc[user_id] == 0].index
    
    # create a dictionary to store the score of each not watched movie
    movie_scores = {}
    
     # iterate over each similar user
    for user in similar_users.index:
        # get the ratings of the user for not watched movies
        user_ratings = ratings_matrix.loc[user][not_watched]

        # calculate the cosine similarity score between the user and input user
        similarity_score = combined_score_matrix_cosine_and_leniency_df[user_id][user]

        # multiply the ratings with the similarity score and add to the movie_scores dictionary
        for movie, rating in user_ratings.items():
            if movie in movie_scores:
                movie_scores[movie] += rating * similarity_score
            else:
                movie_scores[movie] = rating * similarity_score
    
    # sort the movie_scores dictionary by value in descending order
    sorted_scores = sorted(movie_scores.items(), key=lambda x: x[1], reverse=True)
    
    # get the top 5 movies from the sorted_scores
    top_5_movies = [x[0] for x in sorted_scores[:5]]
    
    return top_5_movies
    

userId = 1
top_5_recommended_movies = recommend_movies(userId)
movie_titles = complete_df.loc[complete_df['movieId'].isin(top_5_recommended_movies), 'original_title'].tolist()
print(f"Recommended movies for user {userId} are: ")
print()
unique_movie_titles = set(movie_titles)
for titles in unique_movie_titles:
    print(titles)

Recommended movies for user 1 are:

Rebecca
Reservoir Dogs
Once Were Warriors
Donnie Darko
The Passion of Joan of Arc

In [ ]:
file_path = r'C:\Users\KIIT\Desktop\MINOR_PROJECT\Datasets\combined_score_matrix_cosine_and_leniency_df(2).csv'
combined_score_matrix_cosine_and_leniency_df.to_csv(file_path,index=True)

In [ ]:
user_leniency_matrix

In [ ]:
file_path = r'C:\Users\KIIT\Desktop\MINOR_PROJECT\Datasets\users-leniency-matrix(2).csv'
user_leniency_matrix.to_csv(file_path,index=True)

In [ ]:
user_leniency_matrix